# uv 配置文件
# 参考: https://docs.astral.sh/uv/configuration/

[tool.uv]
# Python版本管理
python-downloads = "automatic"

# 依赖解析配置
resolution = "highest"
prerelease = "disallow"

# 缓存配置
cache-dir = ".uv-cache"
link-mode = "copy"

# 索引配置
index-url = "https://pypi.org/simple"
extra-index-url = []

# 信任的主机
trusted-hosts = []

# 构建配置
compile-bytecode = true
no-build-isolation = false

# 网络配置
timeout = 300
retries = 3

# 并发配置
concurrent-downloads = 50
concurrent-builds = 4

[tool.uv.sources]
# 可以在这里配置特定包的源
# torch = { url = "https://download.pytorch.org/whl/cu118" }

[tool.uv.pip]
# pip兼容配置
compile-bytecode = true
no-deps = false
no-build-isolation = false

[tool.uv.workspace]
# 工作空间配置（如果需要多包项目）
members = []
